apiVersion: ENC[AES256_GCM,data:UyA=,iv:skZ6dO263s7qBZ82MTFkVFqi+SmSwyJDpyn9kd4UEFM=,tag:wD2Wgvft9VMJoFwkJ0nOTw==,type:str]
kind: ENC[AES256_GCM,data:fvTdnsHr,iv:FsgnI4Rp6+sy9KIcryiD7jJyfN7xBmwCOAW8MA9DamY=,tag:ltP4y1eDSP1uNEE1GLIHwQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:fWN8HxlPvNNtABlCK3MaG+s=,iv:bMBjEm31VDIk012gSAdQ2ZO/0Q68hUh3BBedAeuy5rc=,tag:ecmjfuDzi9ItC9TUoxX6TA==,type:str]
type: ENC[AES256_GCM,data:+zp28vqI,iv:TlGrhySF7lf2nt2ViH9YE059BYUZ4UgsaW99KE91QPE=,tag:hdFZkPSjB21SHpan8CtYFw==,type:str]
stringData:
    postgres-password: ENC[AES256_GCM,data:UnO6775hcEQIs/6uHUon,iv:vo2IqbzY5zu4KbH7g5rDKCGKi0x3uTWZvmEusrayXsk=,tag:LRsV+b+t/YNJC7fUzYNZpw==,type:str]
    password: ENC[AES256_GCM,data:hsdFZoEOuSkXwSXJdfAZ,iv:ceJlKGEJOemx2s9jxBSGPq2fi/Kcc+HAQFbO25qZmig=,tag:BkMW7Rg++SAwRCyGdbSuVQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-01T11:38:03Z"
    mac: ENC[AES256_GCM,data:JTobd8H/WZLh2hySXYIx/EsOprCcrzTEfvgKBq/scZzJXMTcPV1iFhHDBlgW1WUx2en3yMQ5iLNpeuQkbJBmJx9XhNU8mqt1Tw8HtNQWp/fqr9koK9WSGz0PTqkrEKDyS68YFXzwvNyw1bQl4/qGS9ZfSNMI65LHm3dY8Cu3SlQ=,iv:aLsi6HOw35SwtLL7Z6flVh86vCWuyGziOfPQonX3nl8=,tag:CoRVMGhZ+YVez7CX2FRNGw==,type:str]
    pgp:
        - created_at: "2025-04-01T10:41:27Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3lQW6xt5AbAARAAsFYRQC4kbI0INvW57H2nIR7X3WbcYHRw9f+8qFTl9xzS
            VzaY8TPn9P3No7buLG+BBwi+Tu2sQpwp1vxptiHj8N6+MUOc0xu0r7aLSfoYpynG
            s2Rs27+aQJALXd65ZrgET9wBtpvS9Dj+Ylqwnf3MfllEsdxPL42+TS5fUR41RNVO
            EMHQSv1wVL0vUtYsw9vojNH1i6qHDW6/kb7vuNVXb0NKS49db92sNBEn+/Jkhbia
            Co9W7aRIjuQV0owrPgY7eRXsVl2++B+AngP87VhZcqsDHo6ZaddmRFcIF0YbdPsz
            PIaTfDpMzMeQUK1H17qz2uGmHicyV8nBQjOs+rQQH2f4y3mKC4LmiNaG2cRMeSJR
            PzsQ3GIKkpW9iqz43z3PlQfv7e4H0MSKDAnBk07p8YyhQDQb7RTw2EBBFUcdGvNx
            o6hYZOeSSmS/lYdElyvuPi0PI0RCx4prfP3wekYPCnuNul2g9uqfRgFyrNv0rLRs
            3lvdiHy0MSdy1GzLEIVKS2dZDoAVlTQMxmz6dP0+Dp3ZJaoZUgBRcVSPXxnHmlWh
            9YzSQ7FJ3R8ub8L0G/AlYvKkj20Nd5qIU7L9f7OMbQpNRJGNT/jXhRlbvPqoVJm/
            2sH/21iLajFF1blEDraig+BXvS33fKzUefQeFtoBgKcNKcURL7l7Bfa0m7BQNoHS
            XgHbF1YL5P2Gf87ZcZXXJ1niw3f7mLv1oSEEgrDYCOCPqbYSW1l3UlPT1MpQ5dJK
            3tFEeh2IxzwN0vIyY/8F6qX9ui9bRBseUD/xkq3997y39JI2dLG0dkOmngT0Uss=
            =VFDe
            -----END PGP MESSAGE-----
          fp: 68C93B37CB74875F
    unencrypted_suffix: _unencrypted
    version: 3.7.3
