apiVersion: ENC[AES256_GCM,data:V2I=,iv:5wqedC32+cTWaBV5j32nZiOtKq5i9IjfXd146UD3iK4=,tag:HJ5K3E1398w+T/58mLlI/g==,type:str]
kind: ENC[AES256_GCM,data:vWJJVTJC,iv:LGrqtmbKQOmnPAS2nFsLFJop770KswM7qd69wwR7Cnw=,tag:y4RFna9Wiv+wb3x2uym23Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:0GeuKpR3yNfbzYDXOqH2gMJC,iv:sMdCUdNhnXBxUa7nNLNS8AgfrVjbMyVejI3exs62Osc=,tag:lzqPska2BvfU0j6KK4mtBg==,type:str]
type: ENC[AES256_GCM,data:QGYeYXWT,iv:VRk8PsgkoyrJoADopWhb1xC0GyqN3JZRaP7o7nRF724=,tag:enrOZLQ1qTI5elFQSOQ/+Q==,type:str]
stringData:
    BANK_POSTGRES_HOST: ENC[AES256_GCM,data:X80Tj1jezMpAwvdCCZu08iVlxDN5ovpqEXS1,iv:jWz/9eXHjeH6Lx8gRGO7Cb9hwF74P8fNfHuL8e02gk0=,tag:7oMlQTfkxBDSrzRxpnUFlQ==,type:str]
    BANK_POSTGRES_DATABASE: ENC[AES256_GCM,data:MZEKL35DaUaXq/Bm1ROwsfo=,iv:Ggo91mYrostTjsF4SC/bphtriuB98OmtXqhlXZMds1I=,tag:h8S/QsPJvev/S8OoBcyqSw==,type:str]
    BANK_POSTGRES_USERNAME: ENC[AES256_GCM,data:YkGREXTN2od5M1I=,iv:M0nXt4gk1cLGF9E4rplM5xko6uue5y+5OeHi7M8CTAo=,tag:xvl2L3ZDLQ8d8J3aAG3ljA==,type:str]
    BANK_POSTGRES_PASSWORD: ENC[AES256_GCM,data:Dl+vEQtvyenRXDJvwOQr,iv:aw6oRHhovEXgSs1NYOUKaQ81J1r7XpBua14T5wGVJIc=,tag:YzhVPCf5xghBNr+mNAWX1g==,type:str]
    BANK_POSTGRES_AUTOMIGRATE: ENC[AES256_GCM,data:DyGZWg==,iv:D7TSauuyK8fme5b6tFhv6++q/Yb6QsOtUxtd+7sapNM=,tag:o3JaipfsLOpbqVrBXNk3gA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-01T10:51:48Z"
    mac: ENC[AES256_GCM,data:H3OvlfyTBQN9nTvdeSkkZxwrOUW9tbXYNf69uJl/PjzIKWv6ApCkNUPiKoqDYhg2BgNM47hYCIhMKU4sV2hn/IlV+RkqwDH4kEuXgCo+AuwGBitreqpgUbYte2p/1pkMDM7bq0Ls4dHuOGn8gQmiw9ieC3Dg+34eKe8z/zoduWU=,iv:vUMdWY/6DMZBs9F2C3rUjR3kct1qs/qAy7BmRa2NlFM=,tag:Fso8s3o8jJ2e74ScQgjWOA==,type:str]
    pgp:
        - created_at: "2025-04-01T10:43:10Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3lQW6xt5AbAAQ/7B0kuvPanK5jSBxzv3eH/wPRQQDsAhnPmKVzdoFYtsrKU
            cciDfxP1sbRNtavAztwzNiK4tpj1QWeIYkx3LLjH/MpuRo7SlBS7I06qXmAtC+oi
            /PSanB7fVUDvTYjzGBQu2qkS7jAOKZoWqoyL+UdHlqaGjhxqJjDb6RcEI80/R/3u
            9vQiqml6ay5l2nKUd8GLdkjjt4MTf0jDHw+5TUGhslNryAj+0FxVHOJOg/iV0ewk
            F36uYsCMv7jNVT99TX8OKHZQrywLRYXVetqIEM5Ibvm0lkAVH6eusEZb9FbFy2WO
            0w5KKiF0WT7u/fOuC2ALiv4kAN/fCaz+xPosp5ig6rN5D+7911L2VFEsaDP4SLtq
            1ZC8jJiVBW0jURxiMgtvYZ6oq7TRokiFgrkBJu1sx4fBehdopRsFDIgQ8slzRUwU
            FAUVB1kM3qCAr43eoyUQRxahZ4rbUm7yCDY1yT2O78+4/kIyiZoqZqSVWVkq/iX8
            TBMHaEvEwLQOWsViCpqLYcCBFzJD3K7wR/YI1VmKEnNUA8NvfqAgzmgfJUQldBKl
            o1U+qTjsz0N8D5JBCzvcYTa/wlhE0KAjUoM5XMV44qPAmQVZW3ZAFLwme/UmVPfZ
            jbU5AuAcfyXheP8X2rEshoOXCHBCDK4gc7Y+CvtGKJkO7zF+aNYhNHRz95+8SGDS
            XgEJKqcjsUXIzikKuSzsB0I6MXd+LdM8hq1zZNLVBwyc1ImG8BtmFE7tiPBIOhy8
            /cRYURIdiFViQoQwWWfoA18S7L1Iabbt2qXHm7D6pt7x9CosQjgRhWhrXWyubT8=
            =69AS
            -----END PGP MESSAGE-----
          fp: 68C93B37CB74875F
    unencrypted_suffix: _unencrypted
    version: 3.7.3
