apiVersion: v2

name: transaction
description: A Helm chart for Kubernetes
type: application

version: 0.1.0
appVersion: "1.0.0"

dependencies:
- condition: postgresql.enabled
  name: postgresql 
  repository: https://charts.bitnami.com/bitnami
  version: 16.6.0